export const BATTLEFIELD_LAYER_ORDER = [
  "terrain",
  "ground-foreground",
  "world-rings",
  "world-effects",
  "world-entities",
  "world-focus",
  "lighting",
  "screen-overlay"
] as const;

export type BattlefieldLayerId = (typeof BATTLEFIELD_LAYER_ORDER)[number];

export const BATTLEFIELD_RUNTIME_ASSET_KEYS = [
  "environment-base",
  "entrance-route-rear",
  "entrance-shell",
  "entrance-route-ground-foreground",
  "entrance-route-foreground",
  "warden-source",
  "warden-basic-attack-source",
  "warden-shield-slam-source",
  "warden-hit-source",
  "warden-guard-source",
  "warden-downed-source",
  "raider-source",
  "raider-north-source",
  "raider-east-source",
  "raider-west-source",
  "raider-attack-source",
  "raider-downed-source",
  "slinger-source",
  "slinger-north-source",
  "slinger-east-source",
  "slinger-west-source",
  "slinger-attack-source",
  "slinger-downed-source",
  "bulwark-source",
  "bulwark-north-source",
  "bulwark-east-source",
  "bulwark-west-source",
  "bulwark-attack-source",
  "bulwark-downed-source",
  "captain-source",
  "captain-north-source",
  "captain-east-source",
  "captain-west-source",
  "captain-attack-source",
  "captain-downed-source",
  "warm-light-overlay",
  "hostile-faction-ring",
  "shield-slam-impact",
  "warden-selection-ring",
  "static-scene-depth"
] as const;
